# Generated by Django 2.2.3 on 2019-08-08 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('document', models.CharField(max_length=100)),
                ('revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(64)])),
                ('path', models.CharField(max_length=200)),
                ('hash_type', models.CharField(choices=[('B', 'Bitstream'), ('R', 'Rendered')], default='B', max_length=1)),
                ('search_path', models.CharField(max_length=200)),
                ('end_commit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash_end_commit', to='olaaf_django.Commit')),
                ('start_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_start_commit', to='olaaf_django.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=10)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olaaf_django.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olaaf_django.Edition'),
        ),
        migrations.AddIndex(
            model_name='hash',
            index=models.Index(fields=['path', 'value', 'hash_type'], name='olaaf_djang_path_a14323_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hash',
            unique_together={('path', 'value', 'hash_type')},
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['repository', 'date'], name='olaaf_djang_reposit_7ed802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('repository', 'date')},
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['edition', 'sha'], name='olaaf_djang_edition_ff91a4_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['date', 'id'], name='olaaf_djang_date_cf02d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('edition', 'sha')},
        ),
    ]
