# Generated by Django 2.2.5 on 2019-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='edition',
            name='olaaf_djang_reposit_7ed802_idx',
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('repository', 'name')},
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['repository', 'name'], name='olaaf_djang_reposit_614433_idx'),
        ),
    ]
