# Generated by Django 2.2.5 on 2019-11-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
