# Generated by Django 2.2.3 on 2019-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='hash_type',
            field=models.CharField(choices=[('B', 'Bitstream'), ('R', 'Rendered')], default='B', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('edition', 'sha')},
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('repository', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hash',
            unique_together={('path', 'value')},
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['edition', 'sha'], name='olaaf_djang_edition_ff91a4_idx'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['repository', 'date'], name='olaaf_djang_reposit_7ed802_idx'),
        ),
        migrations.AddIndex(
            model_name='hash',
            index=models.Index(fields=['path', 'value'], name='olaaf_djang_path_5a6a53_idx'),
        ),
        migrations.AddIndex(
            model_name='hash',
            index=models.Index(fields=['start_commit'], name='olaaf_djang_start_c_512bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='hash',
            index=models.Index(fields=['end_commit'], name='olaaf_djang_end_com_8a0a72_idx'),
        ),
    ]
