# Generated by Django 2.2.5 on 2019-11-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0002_auto_20191115_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hash',
            unique_together={('path', 'value', 'hash_type', 'start_commit')},
        ),
    ]
