# Generated by Django 2.2.5 on 2019-11-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0003_auto_20191126_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateField(),
        ),
    ]
