# Generated by Django 2.2.5 on 2020-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0004_auto_20191127_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
