# Generated by Django 2.2.5 on 2020-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0005_publication_revoked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=13),
        ),
    ]
