# Generated by Django 3.0.5 on 2020-04-06 18:03

from django.db import migrations
import olaaf_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0006_auto_20200406_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='url',
            field=olaaf_django.models.PathUrlField(max_length=260),
        ),
    ]
