# Generated by Django 2.2.5 on 2020-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0007_auto_20200406_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=22),
        ),
    ]
