# Generated by Django 2.2.5 on 2020-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0008_auto_20200625_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='core_version',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
