# Generated by Django 2.2.5 on 2020-08-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0009_publication_core_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='document',
        ),
    ]
