# Generated by Django 3.2.16 on 2023-04-06 14:00

from django.db import migrations


def forward(apps, schema_editor):
    Path = apps.get_model("olaaf_django", "Path")
    for path in Path.objects.all():
        if path.search_path[-1] != '|':
            path.search_path += '|'
            path.save()


def backward(apps, schema_editor):
    Path = apps.get_model("olaaf_django", "Path")
    for path in Path.objects.all():
        if path.search_path[-1] == '|':
            path.search_path = path.search_path[:-1]
            path.save()


class Migration(migrations.Migration):

    dependencies = [
        ('olaaf_django', '0011_auto_20201022_1907'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
