# Generated by Django 2.2.3 on 2019-07-02 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(64)])),
                ('path', models.CharField(max_length=200)),
                ('end_commit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hash_end_commit', to='transient_auth.Commit')),
                ('start_commit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hash_start_commit', to='transient_auth.Commit')),
            ],
        ),
    ]
