on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - name: Set up Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"

      - name: Upgrade pip
        run: |
          pip install --upgrade pip setuptools wheel

      - name: install taf
        run: |
          git clone https://github.com/openlawlibrary/taf
          pip install -e taf
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Test with pytest
        run: |
          pytest olaaf_django/tests
